package datastore

import "reflect"

// RevisionReceiver is implemented by an item type that wants the revision of
// the item a read produced.
//
// [Client.Get] returns a revision directly. A query, a scan or a batch get read
// many items into a slice, which has nowhere to put a second value per element,
// so an item type that intends to write back what it read says so:
//
//	type Order struct {
//	    Total int `json:"total"`
//
//	    rev datastore.Revision
//	}
//
//	func (o *Order) SetRevision(r datastore.Revision) { o.rev = r }
//	func (o Order) Revision() datastore.Revision      { return o.rev }
//
// Types generated by `celerity schema codegen` implement this, so an application
// using generated item types has it already. Hand-written types implement it
// where they need it, which is the case above.
//
// An item type that does not implement this is read exactly as before. The
// revision is still taken off the item either way, since it is reserved.
type RevisionReceiver interface {
	SetRevision(Revision)
}

var revisionReceiver = reflect.TypeFor[RevisionReceiver]()

// DeliverRevisions hands each item its own revision, for a provider that has
// just filled a destination from a read of many items. Revisions are in the
// order the items were read.
//
// Does nothing unless the item type implements [RevisionReceiver].
func DeliverRevisions(out any, revisions []Revision) {
	if len(revisions) == 0 {
		return
	}
	destination := reflect.ValueOf(out)
	if destination.Kind() != reflect.Pointer || destination.IsNil() {
		return
	}
	items := destination.Elem()
	if items.Kind() != reflect.Slice {
		return
	}
	if !reflect.PointerTo(items.Type().Elem()).Implements(revisionReceiver) {
		return
	}

	for i := 0; i < items.Len() && i < len(revisions); i++ {
		receiver, ok := items.Index(i).Addr().Interface().(RevisionReceiver)
		if ok {
			receiver.SetRevision(revisions[i])
		}
	}
}
