package main

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/suite"
)

// The generated file is what links a deploy target's platform packages into an
// application, so these cases pin down that a target produces exactly the
// imports it needs and nothing else.
type PlatformTestSuite struct {
	suite.Suite
}

func TestPlatformTestSuite(t *testing.T) {
	suite.Run(t, new(PlatformTestSuite))
}

func (s *PlatformTestSuite) Test_a_target_links_exactly_the_packages_it_needs() {
	cases := []struct {
		name         string
		target       string
		wantImports  []string
		wantExcluded []string
	}{
		{
			name:        "a serverless target links an adapter and a provider",
			target:      TargetAWSServerless,
			wantImports: []string{"serverless/aws", "resources/aws"},
		},
		{
			// A containerised deployment is served by the Celerity runtime over
			// the IPC stream, so no adapter is involved and linking one would
			// pull a cloud SDK the binary never calls.
			name:         "a containerised target links no adapter",
			target:       TargetAWS,
			wantImports:  []string{"resources/aws"},
			wantExcluded: []string{"serverless/aws"},
		},
	}

	for _, tc := range cases {
		s.Run(tc.name, func() {
			got, err := GeneratePlatformFile("main", tc.target, GenerateOptions{})

			s.Require().NoError(err)
			s.True(strings.HasPrefix(got, "// Code generated by celerity-go"),
				"the generated file lacks the generated-code marker:\n%s", got)
			s.Contains(got, "package main\n")

			for _, want := range tc.wantImports {
				s.Contains(got, want)
			}
			for _, unwanted := range tc.wantExcluded {
				s.NotContains(got, unwanted)
			}
		})
	}
}

func (s *PlatformTestSuite) Test_the_generated_file_matches_the_package_it_is_written_into() {
	got, err := GeneratePlatformFile("orders", TargetAWSServerless, GenerateOptions{})

	s.Require().NoError(err)
	s.Contains(got, "package orders\n")
}

func (s *PlatformTestSuite) Test_an_unsupported_target_is_refused_by_name() {
	cases := []struct {
		name       string
		target     string
		wantPhrase string
	}{
		{
			// Mapped but not built yet, which is a different problem from a typo
			// and says so, rather than failing later as an unresolvable import.
			name:       "a known target the SDK cannot build for yet",
			target:     TargetAzureServerless,
			wantPhrase: "does not support",
		},
		{
			name:       "a target that does not exist",
			target:     "aws-lamda",
			wantPhrase: "unknown deploy target",
		},
	}

	for _, tc := range cases {
		s.Run(tc.name, func() {
			_, err := GeneratePlatformFile("main", tc.target, GenerateOptions{})

			var unsupported *UnsupportedTargetError
			s.Require().ErrorAs(err, &unsupported)
			s.Contains(err.Error(), tc.wantPhrase)
			s.Contains(err.Error(), TargetAWSServerless, "the error should list what is supported")
		})
	}
}

func (s *PlatformTestSuite) Test_a_deployment_does_not_link_what_only_a_session_reads() {
	// A deployed function has no use for a Redis client and should not carry
	// one, and a session builds its own artefact, so the two need not match.
	for _, target := range []string{TargetAWS, TargetAWSServerless} {
		s.Run(target, func() {
			got, err := GeneratePlatformFile("main", target, GenerateOptions{})

			s.Require().NoError(err)
			s.NotContains(got, LocalConfig)
		})
	}
}

func (s *PlatformTestSuite) Test_a_local_session_links_what_it_reads_as_well() {
	// Without this, `celerity dev` would read no configuration and a developer
	// would have to add an import to get parity with Node and Python.
	for _, target := range []string{TargetAWS, TargetAWSServerless} {
		s.Run(target, func() {
			got, err := GeneratePlatformFile("main", target, GenerateOptions{Local: true})

			s.Require().NoError(err)
			s.Contains(got, LocalConfig)
			s.Contains(got, "local development session",
				"the file should say why it differs from a deployment's")
			// And still everything the target itself needs.
			s.Contains(got, "/resources/aws")
		})
	}
}

func (s *PlatformTestSuite) Test_an_import_is_never_written_for_a_package_that_does_not_exist() {
	// A target whose other packages are ready is not held back by one that is
	// not, and an unresolvable import says nothing about why it failed.
	got, err := GeneratePlatformFile("main", TargetAWSServerless, GenerateOptions{})

	s.Require().NoError(err)
	s.NotContains(got, "/resources/gcp", "another platform's packages are not built")
	s.Contains(got, "/serverless/aws")
	s.Contains(got, "/resources/aws")
	s.Contains(got, "/config/aws")
}
