package main

import (
	"errors"
	"strings"
	"testing"
)

// The generated file is what links a deploy target's platform packages into an
// application, so these cases pin down that a target produces exactly the
// imports it needs and nothing else.

func TestGeneratePlatformFile(t *testing.T) {
	cases := []struct {
		name         string
		target       string
		wantImports  []string
		wantExcluded []string
	}{
		{
			name:        "a serverless target links an adapter and a provider",
			target:      TargetAWSServerless,
			wantImports: []string{"serverless/aws", "resources/aws"},
		},
		{
			// A containerised deployment is served by the Celerity runtime over
			// the IPC stream, so no adapter is involved and linking one would
			// pull a cloud SDK the binary never calls.
			name:         "a containerised target links no adapter",
			target:       TargetAWS,
			wantImports:  []string{"resources/aws"},
			wantExcluded: []string{"serverless/aws"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := GeneratePlatformFile("main", tc.target)
			if err != nil {
				t.Fatalf("GeneratePlatformFile returned %v", err)
			}

			if !strings.HasPrefix(got, "// Code generated by celerity-go") {
				t.Errorf("generated file lacks the generated-code marker:\n%s", got)
			}
			if !strings.Contains(got, "package main\n") {
				t.Errorf("generated file has the wrong package clause:\n%s", got)
			}

			for _, want := range tc.wantImports {
				if !strings.Contains(got, want) {
					t.Errorf("generated file does not import %s:\n%s", want, got)
				}
			}
			for _, unwanted := range tc.wantExcluded {
				if strings.Contains(got, unwanted) {
					t.Errorf("generated file imports %s and should not:\n%s", unwanted, got)
				}
			}
		})
	}
}

func TestGeneratePlatformFileUsesThePackageItIsWrittenInto(t *testing.T) {
	got, err := GeneratePlatformFile("orders", TargetAWSServerless)
	if err != nil {
		t.Fatalf("GeneratePlatformFile returned %v", err)
	}
	if !strings.Contains(got, "package orders\n") {
		t.Errorf("generated file has the wrong package clause:\n%s", got)
	}
}

func TestUnsupportedTargets(t *testing.T) {
	cases := []struct {
		name       string
		target     string
		wantPhrase string
	}{
		{
			// Mapped but not built yet, which is a different problem from a typo
			// and says so, rather than failing later as an unresolvable import.
			name:       "a known target the SDK cannot build for yet",
			target:     TargetAzureServerless,
			wantPhrase: "does not support",
		},
		{
			name:       "a target that does not exist",
			target:     "aws-lamda",
			wantPhrase: "unknown deploy target",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := GeneratePlatformFile("main", tc.target)

			var unsupported *UnsupportedTargetError
			if !errors.As(err, &unsupported) {
				t.Fatalf("error = %v, want an UnsupportedTargetError", err)
			}
			if !strings.Contains(err.Error(), tc.wantPhrase) {
				t.Errorf("error %q does not contain %q", err, tc.wantPhrase)
			}
			if !strings.Contains(err.Error(), TargetAWSServerless) {
				t.Errorf("error %q does not list the supported targets", err)
			}
		})
	}
}
