package handler

import (
	"context"
	"strconv"
)

// OutboundMessage is one message a handler sends to a connected WebSocket
// client.
type OutboundMessage struct {
	ConnectionID string
	// Message is sent to the socket exactly as given. When IsBinary is set it
	// must be in the Celerity Binary Message Format, which
	// [FrameBinaryMessage] produces: a client reads every non-reserved binary
	// frame as a framed message, so raw bytes are read as a route length and a
	// route rather than as a payload.
	Message  []byte
	IsBinary bool
	// InformClientsOnLoss names connections to notify if this message cannot be
	// delivered.
	InformClientsOnLoss []string
	// MessageID identifies the message to the runtime, for acknowledgement
	// between nodes and in loss events. Generated by the runtime when empty,
	// which is the right choice unless the caller needs to match a loss event
	// back to what it sent.
	//
	// Not the id the client sees: the runtime sends Message to the socket
	// exactly as given, so a client-visible id belongs in the payload.
	MessageID string
	// Caller is the connection that caused this message to be sent, carried
	// through to the loss event. Only meaningful alongside InformClientsOnLoss.
	Caller string
}

// WebSocketSender pushes messages to connected clients.
//
// Under the Celerity runtime it is the IPC stream's side channel; under a
// serverless adapter it is the provider's own push API, such as the API Gateway
// Management API. A handler reaches it through celerity.WebSocketSenderFrom and
// does not need to know which.
type WebSocketSender interface {
	// Send delivers every message and blocks until the outcome is known.
	//
	// A partial failure returns a [SendError] naming exactly which messages
	// failed, because a client cannot deduplicate: a message reaches it as a
	// bare frame with no id, so resending one that already arrived is visible to
	// the application.
	Send(ctx context.Context, messages ...OutboundMessage) error
}

// SendError reports which messages in a send failed.
type SendError struct {
	Failures []SendFailure
}

// SendFailure names one message that could not be delivered, by its index in
// the batch that was sent.
type SendFailure struct {
	Index        int
	ConnectionID string
	Error        string
}

func (e *SendError) Error() string {
	if len(e.Failures) == 1 {
		return "celerity: websocket send failed for 1 message: " + e.Failures[0].Error
	}
	return "celerity: websocket send failed for " + strconv.Itoa(len(e.Failures)) + " messages"
}

// Failed reports whether the message at index failed.
func (e *SendError) Failed(index int) bool {
	for _, f := range e.Failures {
		if f.Index == index {
			return true
		}
	}
	return false
}
