// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.0
// source: celerity/runtime/v1/runtime.proto

// The contract between the Celerity runtime and a handlers executable running
// as a separate process, used by SDKs for ahead-of-time compiled languages.
//
// Everything the runtime needs in order to make a decision is typed. Everything
// else is `bytes`, which the runtime moves without inspecting. The runtime
// routes, times out, traces and meters on the envelope.

package celerityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HandlerRuntimeService_EventStream_FullMethodName = "/celerity.runtime.v1.HandlerRuntimeService/EventStream"
)

// HandlerRuntimeServiceClient is the client API for HandlerRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// One long-lived bidirectional stream carries everything: events, results,
// configuration, WebSocket sends, handler-to-handler invocation, cancellation
// and shutdown.
type HandlerRuntimeServiceClient interface {
	EventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HandlerMessage, RuntimeMessage], error)
}

type handlerRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHandlerRuntimeServiceClient(cc grpc.ClientConnInterface) HandlerRuntimeServiceClient {
	return &handlerRuntimeServiceClient{cc}
}

func (c *handlerRuntimeServiceClient) EventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HandlerMessage, RuntimeMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HandlerRuntimeService_ServiceDesc.Streams[0], HandlerRuntimeService_EventStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HandlerMessage, RuntimeMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HandlerRuntimeService_EventStreamClient = grpc.BidiStreamingClient[HandlerMessage, RuntimeMessage]

// HandlerRuntimeServiceServer is the server API for HandlerRuntimeService service.
// All implementations must embed UnimplementedHandlerRuntimeServiceServer
// for forward compatibility.
//
// One long-lived bidirectional stream carries everything: events, results,
// configuration, WebSocket sends, handler-to-handler invocation, cancellation
// and shutdown.
type HandlerRuntimeServiceServer interface {
	EventStream(grpc.BidiStreamingServer[HandlerMessage, RuntimeMessage]) error
	mustEmbedUnimplementedHandlerRuntimeServiceServer()
}

// UnimplementedHandlerRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHandlerRuntimeServiceServer struct{}

func (UnimplementedHandlerRuntimeServiceServer) EventStream(grpc.BidiStreamingServer[HandlerMessage, RuntimeMessage]) error {
	return status.Errorf(codes.Unimplemented, "method EventStream not implemented")
}
func (UnimplementedHandlerRuntimeServiceServer) mustEmbedUnimplementedHandlerRuntimeServiceServer() {}
func (UnimplementedHandlerRuntimeServiceServer) testEmbeddedByValue()                               {}

// UnsafeHandlerRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HandlerRuntimeServiceServer will
// result in compilation errors.
type UnsafeHandlerRuntimeServiceServer interface {
	mustEmbedUnimplementedHandlerRuntimeServiceServer()
}

func RegisterHandlerRuntimeServiceServer(s grpc.ServiceRegistrar, srv HandlerRuntimeServiceServer) {
	// If the following call pancis, it indicates UnimplementedHandlerRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HandlerRuntimeService_ServiceDesc, srv)
}

func _HandlerRuntimeService_EventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HandlerRuntimeServiceServer).EventStream(&grpc.GenericServerStream[HandlerMessage, RuntimeMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HandlerRuntimeService_EventStreamServer = grpc.BidiStreamingServer[HandlerMessage, RuntimeMessage]

// HandlerRuntimeService_ServiceDesc is the grpc.ServiceDesc for HandlerRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HandlerRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "celerity.runtime.v1.HandlerRuntimeService",
	HandlerType: (*HandlerRuntimeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventStream",
			Handler:       _HandlerRuntimeService_EventStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "celerity/runtime/v1/runtime.proto",
}
